CREATE TABLE IF NOT EXISTS ENDERECO(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    RUA VARCHAR(36),
    NUMERO VARCHAR(12),
    CIDADE VARCHAR(36),
    BAIRRO VARCHAR(36)
);

CREATE TABLE IF NOT EXISTS PACIENTE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    SOBRENOME VARCHAR(48),
    RG VARCHAR(10),
    DATA_ALTA TIMESTAMP WITHOUT TIME ZONE,
    ENDERECO_ID INT
);

CREATE TABLE IF NOT EXISTS DENTISTA(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    SOBRENOME VARCHAR(48),
    MATRICULA VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS USUARIO(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50),
    EMAIL VARCHAR(50),
    SENHA VARCHAR(50),
    NIVEL_ACESSO VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS CONSULTA(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DATA DATE,
    PACIENTE_ID INT,
    DENTISTA_ID INT
);

INSERT INTO DENTISTA (NOME, SOBRENOME, MATRICULA) VALUES ('MARCOS', 'OLIVEIRA', '1234');
INSERT INTO DENTISTA (NOME, SOBRENOME, MATRICULA) VALUES ('MARCOS', 'OLIVEIRA', '1234');
INSERT INTO DENTISTA (NOME, SOBRENOME, MATRICULA) VALUES ('MARCOS', 'OLIVEIRA', '1234');
INSERT INTO DENTISTA (NOME, SOBRENOME, MATRICULA) VALUES ('MARCOS', 'OLIVEIRA', '1234');

INSERT INTO USUARIO (NOME, EMAIL,SENHA,NIVEL_ACESSO) VALUES ('TESTER','TESTEGMAILCOM','123','BASICO');
INSERT INTO USUARIO (NOME, EMAIL,SENHA,NIVEL_ACESSO) VALUES ('TESTER','TESTEGMAILCOM','123','BASICO');

INSERT INTO ENDERECO(RUA,NUMERO,CIDADE,BAIRRO) VALUES ('CARLOS WANGNER','1434','AVIACAO','VENANCIO');
INSERT INTO ENDERECO(RUA,NUMERO,CIDADE,BAIRRO) VALUES ('CORONEL AGRA','1434','AVIACAO','VENANCIO');

INSERT INTO PACIENTE (NOME, SOBRENOME,RG,DATA_ALTA,ENDERECO_ID) VALUES ('DARLEI','FEIX','64645465','2022-05-30',1);


